service: mech-trade-back-end

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  corsOrigin: '*'
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-webpack

provider:
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    COGNITO_USER_POOL:
      Ref: CognitoUserPool
    COGNITO_USER_POOL_CLIENT:
      Ref: CognitoUserPoolClient
    CORS_ORIGIN: ${self:custom.corsOrigin}
    DYNAMODB_LISTINGS_TABLE: ${self:service}-listings-table-${opt:stage, self:provider.stage}
    DYNAMODB_LISTINGS_TABLE_GSI1: ${self:service}-listings-table-gsi1-${opt:stage, self:provider.stage}
    DYNAMODB_LISTINGS_TABLE_GSI2: ${self:service}-listings-table-gsi2-${opt:stage, self:provider.stage}
    # DYNAMODB_USERS_TABLE: ${self:service}-users-table-${opt:stage, self:provider.stage}
    # DYNAMODB_USERS_TYPE_GSI: ${self:service}-users-table-type-gsi-${opt:stage, self:provider.stage}
    ENVIRONMENT: ${opt:stage, self:provider.stage}
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: dev

package:
  individually: true
  exclude:
    - "node_modules/**"

functions:
  createListing:
    description: Creates a new listing
    name: lambda-${self:service}-createListing-${opt:stage, self:provider.stage}
    handler: src/handler.createListing
    events:
      - http:
          authorizer: aws_iam
          cors: true
          method: post
          operationId: createListing
          path: create/listing
  createUser:
    description: Creates a new user
    name: lambda-${self:service}-createUser-${opt:stage, self:provider.stage}
    handler: src/handler.createUser
    events:
      - http:
          authorizer: aws_iam
          cors: true
          method: post
          operationId: createUser
          path: create/user

resources:
  # Cognito
  - ${file(src/services/cognito.yml)}
  # DynamoDB
  - ${file(src/services/dynamodb.yml)}
  # S3
  # - ${file(services/s3.yml)}