Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: listing_id
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        # - AttributeName: comment_id
        #   AttributeType: S
        - AttributeName: country_city
          AttributeType: S
        - AttributeName: partition_key
          AttributeType: S
        # - AttributeName: purchase_id
        #   AttributeType: S
        - AttributeName: seller_id
          AttributeType: S
        # - AttributeName: user_id
        #   AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        # Get listings by location
        - IndexName: ${self:provider.environment.DYNAMODB_LISTINGS_TABLE_GSI1}
          KeySchema:
            - AttributeName: country_city
              KeyType: HASH
            - AttributeName: listing_id
              KeyType: RANGE
          Projection:
            NonKeyAttributes: [
              category,
              city,
              country,
              created_at,
              current_price,
              description,
              image_urls,
              is_available,
              seller_id,
              sub_title,
              title
            ]
            ProjectionType: INCLUDE
        # Get listings by category
        - IndexName: ${self:provider.environment.DYNAMODB_LISTINGS_TABLE_GSI2}
          KeySchema:
            - AttributeName: category
              KeyType: HASH
            - AttributeName: listing_id
              KeyType: RANGE
          Projection:
            NonKeyAttributes: [
              city,
              country,
              created_at,
              current_price,
              description,
              image_urls,
              is_available,
              seller_id,
              sub_title,
              title
            ]
            ProjectionType: INCLUDE
        # Get listings for a seller
        - IndexName: ${self:provider.environment.DYNAMODB_LISTINGS_TABLE_GSI3}
          KeySchema:
            - AttributeName: seller_id
              KeyType: HASH
            - AttributeName: listing_id
              KeyType: RANGE
          Projection:
            NonKeyAttributes: [
              category,
              city,
              country,
              created_at,
              current_price,
              description,
              image_urls,
              is_available,
              sub_title,
              title
            ]
            ProjectionType: INCLUDE
        # Get purchases for a buyer
        # TODO
      KeySchema:
        - AttributeName: partition_key
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
      TableName: ${self:provider.environment.DYNAMODB_LISTINGS_TABLE}