Resources:
  # DynamoDB - Listings
  ListingsDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: listingId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: listingId
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      TableName: ${self:provider.environment.DYNAMODB_LISTINGS_TABLE}
  # DynamoDB - Users
  UsersDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      # GlobalSecondaryIndexes:
      #   - IndexName: ${self:provider.environment.DYNAMODB_USERS_TYPE_GSI}
      #     KeySchema:
      #       - AttributeName: itemId
      #         KeyType: HASH
      #     Projection:
      #       ProjectionType: ALL
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}