export const CONSTANTS = {
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    COGNITO_USER_POOL: process.env.COGNITO_USER_POOL,
    COGNITO_USER_POOL_CLIENT: process.env.COGNITO_USER_POOL_CLIENT,
    ENVIRONMENT: process.env.ENVIRONMENT,
    DYNAMODB_LISTINGS_TABLE: process.env.DYNAMODB_LISTINGS_TABLE,
    DYNAMODB_LISTINGS_TABLE_GSI1: process.env.DYNAMODB_LISTINGS_TABLE_GSI1,
    DYNAMODB_LISTINGS_TABLE_GSI2: process.env.DYNAMODB_LISTINGS_TABLE_GSI2,
    DYNAMODB_LISTINGS_TABLE_GSI3: process.env.DYNAMODB_LISTINGS_TABLE_GSI3,
    IS_OFFLINE: process.env.IS_OFFLINE,
    PP_CLIENT_ID: process.env.PP_CLIENT_ID,
    PP_CLIENT_SECRET: process.env.PP_CLIENT_SECRET,
    PP_ENDPOINT: process.env.PP_ENDPOINT,
    S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
    S3_BUCKET: process.env.S3_BUCKET,
    S3_ENDPOINT: process.env.S3_ENDPOINT,
    S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY
};