export const CONSTANTS = {
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    COGNITO_USER_POOL: process.env.COGNITO_USER_POOL,
    COGNITO_USER_POOL_CLIENT: process.env.COGNITO_USER_POOL_CLIENT,
    ENVIRONMENT: process.env.ENVIRONMENT,
    DYNAMODB_LISTINGS_TABLE: process.env.DYNAMODB_LISTINGS_TABLE,
    DYNAMODB_LISTINGS_TABLE_GSI1: process.env.DYNAMODB_LISTINGS_TABLE_GSI1,
    DYNAMODB_LISTINGS_TABLE_GSI2: process.env.DYNAMODB_LISTINGS_TABLE_GSI2,
    DYNAMODB_LISTINGS_TABLE_GSI3: process.env.DYNAMODB_LISTINGS_TABLE_GSI3,
    IS_OFFLINE: process.env.IS_OFFLINE
};